### ISSUE TITLE
Needs plugin.yml please

### ISSUE THREAD

**Issue by SinlesFlyer376** [CraftBlock/McmmoStats#1]
The title plz

**Comment by Curtisdhi** [comment]
What is the plugin.yml for? This isn't a bukkit plugin if that is what you are thinking. It's a web interface for mcmmo's sql database.

**Comment by SinlesFlyer376** [comment]
plugin.yml is so I can download the .phar of this plugin so I can add it to my server

**Comment by Curtisdhi** [comment]
What .phar? And why does your server need a plugin? I am confused.

**Comment by kawohi** [comment]
I would suggest this for mcmmo stats. https://www.spigotmc.org/resources/mcmmo-webstats.3621/

**Comment by SinlesFlyer376** [comment]
Well spigotmc is only used for PC servers I am using pe

**Comment by SinlesFlyer376** [comment]
pmt.mcpe.me makes the .zip into a .phar and the onlway to add a pkugin to pe servers is .phar

**Comment by Curtisdhi** [comment]
*faceplam* You realize this was built for spigot right? Not only that, but depends on the mcmmo mysql database. 
*researchs into what you're even on about* I assume your using this https://www.pocketmine.net/ and think this is a plugin for it? Yeah no, this is a standalone php app that has no clue to pocketmine. You can literally throw it on any php server and give it mysql access to a mcmmo database. Giving it a plugin.yml doesn't magically make it a pocketmine plugin... If you really want a plugin like this for your server, I don't really have the time to port this over for free... But free feel do so. here's the docs for it. http://pocketmine-mp.readthedocs.io/en/latest/plugins.html
